/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: 1225ddf4cee913307a401c0f6d3db92f)
interface __BaseEnv_Env {
  WEATHER_CACHE: KVNamespace;
  ROUTES_DB: D1Database;
  MET_OFFICE_API_KEY: string;
  MET_OFFICE_BPF_API_KEY: string;
  API_KEYS_JSON: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        'MET_OFFICE_API_KEY' | 'MET_OFFICE_BPF_API_KEY' | 'API_KEYS_JSON'
      >
    > {}
}
declare module '*.txt' {
  const value: string;
  export default value;
}
declare module '*.html' {
  const value: string;
  export default value;
}
declare module '*.sql' {
  const value: string;
  export default value;
}
declare module '*.bin' {
  const value: ArrayBuffer;
  export default value;
}
declare module '*.wasm' {
  const value: WebAssembly.Module;
  export default value;
}
declare module '*.wasm?module' {
  const value: WebAssembly.Module;
  export default value;
}
